# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: arthurrabelopro@gmail.com
author_name: p2arthur
contract_name: BoxContract
preset_name: starter
project_name: fullstack_test

